
server:
  port: 8080

jwt:
  secret-key: "secretsecretsecretsecretsecretsecretsecretsecretsecret"
  ACCESS_TOKEN_EXPIRATION: 180000
  REFRESH_TOKEN_EXPIRATION: 604800000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ktb?&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

