name: Java CD

on:
  workflow_run:
    workflows: ["Java CI"] # CI 워크플로우 이름과 정확히 일치해야 함
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ktb-api .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ktb-api

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            script: |
              docker stop ktb-api || true
              docker rm ktb-api || true
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ktb-api:latest
              if [ $(sudo docker ps -a -q -f name=ktb-api) ]; then
              sudo docker stop ktb-api
              sudo docker rm ktb-api
              fi
              sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ktb-api:latest ktb-api
              docker run -d --name ktb-api -p 80:8080 \
                -e SEVER_PORT= ${{ secrets.SEVER_PORT }} \
                -e CLOUD_AWS_CREDENTIALS_ACCESS_KEY= ${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }} \
                -e CLOUD_AWS_CREDENTIALS_SECRET_KEY= ${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_KEY }} \
                -e CLOUD_AWS_REGION_AUTO= ${{ secrets.CLOUD_AWS_REGION_AUTO }} \
                -e CLOUD_AWS_REGION_STATIC= ${{ secrets.CLOUD_AWS_REGION_STATIC }} \
                -e CLOUD_AWS_S3_BUCKET= ${{ secrets.CLOUD_AWS_S3_BUCKET }} \
                -e CLOUD_AWS_STACK_AUTO= ${{ secrets.CLOUD_AWS_STACK_AUTO }} \
                -e JWT_ACCESS_TOKEN_EXPIRATION= ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }} \
                -e JWT_SECRET_KEY= ${{ secrets.JWT_SECRET_KEY }} \
                -e REFRESH_TOKEN_EXPIRATION= ${{ secrets.REFRESH_TOKEN_EXPIRATION }} \
                -e SPRING_DATASOURCE_DRIVER_CLASS_NAME= ${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }} \
                -e SPRING_DATASOURCE_PASSWORD= ${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
                -e SPRING_DATASOURCE_URL= ${{ secrets.SPRING_DATASOURCE_URL }} \
                -e SPRING_DATASOURCE_USERNAME= ${{ secrets.SPRING_DATASOURCE_USERNAME }} \
                -e SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE= ${{ secrets.SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE }} \
                -e SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE= ${{ secrets.SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE }} \
                
            




              ${{ secrets.DOCKERHUB_USERNAME }}/ktb-api:latest
              docker image prune -af